version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci || npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - package.json
    - package-lock.json
    - dist-server/**/* 
    - public/**/* 
    - buildspec-test.yml 
    - Procfile
  discard-paths: no